Make sure cdk lambda and core are on 1.66.0
Errors like the below happen when cdk packages are not all on the same
version:

> secret-traitor@0.1.0 watch /Users/dougnaphas/repos/secret-traitor
> tsc -w
[6:30:03 PM] Starting compilation in watch mode...
lib/hitcounter.ts:35:7 - error TS2322: Type
'import("/Users/dougnaphas/repos/secret-traitor/node_modules/@aws-cdk/core/lib/duration").Duration'
is not assignable to type
'import("/Users/dougnaphas/repos/secret-traitor/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/core/lib/duration").Duration'.
  Types have separate declarations of a private property 'amount'.
35       timeout: cdk.Duration.seconds(20),
         ~~~~~~~
  node_modules/@aws-cdk/aws-lambda/lib/function.d.ts:55:14
    55     readonly timeout?: Duration;
                    ~~~~~~~
    The expected type comes from property 'timeout' which is declared
here on type 'FunctionProps'
lib/secret-traitor-stack.ts:37:7 - error TS2322: Type
'import("/Users/dougnaphas/repos/secret-traitor/node_modules/@aws-cdk/core/lib/duration").Duration'
is not assignable to type
'import("/Users/dougnaphas/repos/secret-traitor/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/core/lib/duration").Duration'.
37       timeout: cdk.Duration.seconds(20),
         ~~~~~~~
  node_modules/@aws-cdk/aws-lambda/lib/function.d.ts:55:14
    55     readonly timeout?: Duration;
                    ~~~~~~~
    The expected type comes from property 'timeout' which is declared
here on type 'FunctionProps'